### ISSUE TITLE
Site (partially) down

### ISSUE THREAD

**Issue by TimTaylor** [rbind/yihui#1584]
Apologies if you're aware but the main landing page (https://yihui.org) seems to be down. Other pages such as https://yihui.org/litedown/ are accessible though.

**Comment by yihui** [comment]
Yes, I was aware of it but failed to figure out the reason last night and gave up in the end since it was too late in the night. I'm  trying to fix it again now. Thank you very much for the report!

**Comment by yihui** [comment]
Fixed now. Thanks again!
